import React,{useState,useEffect,useRef,useCallback} from 'react';
import {profile,projectsPt,projectsEn,filtersPt,filtersEn,experiencePt,experienceEn} from './content';
import folders from './folder-art.json';
import icons from './icons.json';

const ui={
 pt:{
  nav:[['/','início'],['/work/','projetos'],['/about/','sobre']],navigation:'Navegação principal',homeLabel:'Rafael Palmeira, início',language:'Selecionar idioma',skip:'Pular para o conteúdo',resume:'Currículo',socials:'Contato e currículo',
  mobileGreeting:'Olá, ',intro:[
   {title:'Eu desenho produtos.',text:'Sou Lead Product Designer e designer multidisciplinar. Transformo problemas complexos em experiências digitais claras, úteis e humanas.'},
   {title:'Eu conecto sistemas.',before:'No Design Horizontal da ',link:'Vivo · Telefônica Brasil',after:', aproximo estratégia, produto, tecnologia e design para criar direção e consistência entre jornadas.'},
   {title:'Eu amplio o craft.',text:'Há mais de 10 anos, combino pesquisa, interface, design systems, linguagem visual e experimentação com IA para levar uma ideia do princípio ao detalhe.'}
  ],
  viewProject:'Ver projeto',carousel:'Carrossel de projetos',selectProject:'Selecionar projeto',project:'projeto',of:'de',scroll:'Role para explorar',
  workKicker:'Trabalhos selecionados',workTitle:<>Produtos, marcas e histórias.<br/>Cada projeto pede uma forma própria de pensar.</>,filter:'Filtrar projetos por disciplina',found:'projetos encontrados',
  about:{title:'Design que cria direção.',blocks:[
   {text:'Meu trabalho vive no encontro entre lógica e expressão. Uso estratégia, pesquisa e craft para transformar complexidade em experiências que as pessoas entendem e os times conseguem sustentar.'},
   {title:'Eu desenho produtos.',text:'Estruturo jornadas, interfaces e sistemas digitais a partir de necessidades reais, contexto de negócio e decisões claras.'},
   {title:'Eu conecto sistemas.',text:'No Design Horizontal da Vivo · Telefônica Brasil, atuo entre times e unidades de negócio para aproximar produto, tecnologia, comunicação e design.'},
   {title:'Eu lidero pela prática.',text:'Enquadro problemas, facilito decisões e construo princípios, ritos e documentação. Acompanho o trabalho até a entrega, porque direção e execução precisam permanecer conectadas.'},
   {title:'Eu amplio o craft.',text:'Minha formação multidisciplinar atravessa tipografia, identidade, composição, motion e IA. Esse repertório ajuda cada produto a ganhar clareza, ritmo e personalidade.'},
   {text:'Há mais de 10 anos, trabalho com experiências digitais. Hoje estou na Vivo. Antes, passei por Nestlé, Ernst & Young, Publicis Groupe · Sapient AG2 e TeamWorker.'},
   {text:'Também desenvolvi projetos para Bradesco, Itaú Unibanco, Nissan, Adidas, Volvo Trucks, Michelin, Museu do Futebol, Cultura Inglesa, Procter & Gamble, Chevrolet, Sanofi, Pernod Ricard, Outback, Dow AgroSciences e Sabesp.'}
  ],closer:'Clareza para decidir. Sistemas para escalar. ',closerAccent:'Craft para conectar.',musicTitle:'O que toca enquanto penso',musicText:'Kaiser Chiefs para ideias em movimento.',spotify:'Ouvir Kaiser Chiefs no Spotify',contact:'Vamos criar algo relevante',experience:'Onde construí essa trajetória'},
  close:'Fechar projeto',portfolio:'Conheça o portfólio completo',notFound:'Página não encontrada.',back:'Voltar ao início',titles:{home:'Rafael Palmeira · Lead Product Designer',work:'Projetos · Rafael Palmeira',about:'Sobre · Rafael Palmeira'}
 },
 en:{
  nav:[['/','home'],['/work/','work'],['/about/','about']],navigation:'Main navigation',homeLabel:'Rafael Palmeira, home',language:'Select language',skip:'Skip to content',resume:'Resume',socials:'Contact and resume',
  mobileGreeting:'Hello, ',intro:[
   {title:'I design products.',text:'I am a Lead Product Designer and multidisciplinary designer. I turn complex problems into clear, useful and human digital experiences.'},
   {title:'I connect systems.',before:'At ',link:'Vivo · Telefônica Brasil',after:' Horizontal Design, I bring strategy, product, technology and design together to create direction and consistency across journeys.'},
   {title:'I expand the craft.',text:'For over 10 years, I have combined research, interface design, design systems, visual language and AI experimentation to carry ideas from first principle to final detail.'}
  ],
  viewProject:'View project',carousel:'Project carousel',selectProject:'Select project',project:'project',of:'of',scroll:'Scroll to explore',
  workKicker:'Selected work',workTitle:<>Products, brands and stories.<br/>Every project calls for its own way of thinking.</>,filter:'Filter projects by discipline',found:'projects found',
  about:{title:'Design that creates direction.',blocks:[
   {text:'My work lives at the intersection of logic and expression. I use strategy, research and craft to turn complexity into experiences people understand and teams can sustain.'},
   {title:'I design products.',text:'I shape journeys, interfaces and digital systems around real needs, business context and clear decisions.'},
   {title:'I connect systems.',text:'At Vivo · Telefônica Brasil Horizontal Design, I work across teams and business units to bring product, technology, communication and design closer together.'},
   {title:'I lead through practice.',text:'I frame problems, facilitate decisions and build principles, rituals and documentation. I stay close through delivery because direction and execution need to remain connected.'},
   {title:'I expand the craft.',text:'My multidisciplinary background spans typography, identity, composition, motion and AI. This range helps every product gain clarity, rhythm and personality.'},
   {text:'I have worked with digital experiences for over 10 years. Today I am at Vivo. Previously, I worked at Nestlé, Ernst & Young, Publicis Groupe · Sapient AG2 and TeamWorker.'},
   {text:'I have also developed work for Bradesco, Itaú Unibanco, Nissan, Adidas, Volvo Trucks, Michelin, Museu do Futebol, Cultura Inglesa, Procter & Gamble, Chevrolet, Sanofi, Pernod Ricard, Outback, Dow AgroSciences and Sabesp.'}
  ],closer:'Clarity to decide. Systems to scale. ',closerAccent:'Craft to connect.',musicTitle:'What plays while I think',musicText:'Kaiser Chiefs for ideas in motion.',spotify:'Listen to Kaiser Chiefs on Spotify',contact:'Let’s create something relevant',experience:'Where I built this journey'},
  close:'Close project',portfolio:'Explore the full portfolio',notFound:'Page not found.',back:'Back to home',titles:{home:'Rafael Palmeira · Lead Product Designer',work:'Work · Rafael Palmeira',about:'About · Rafael Palmeira'}
 }
};

function getInitialLanguage(){try{return localStorage.getItem('rp-language')==='en'?'en':'pt'}catch{return'pt'}}

function Icon({kind='arrow'}){return <span className="icon" aria-hidden="true" dangerouslySetInnerHTML={{__html:icons[{linkedin:0,instagram:1,cv:2,arrow:3,down:4}[kind]]||''}}/>}
function Socials({t}){return <div className="rp-socials" aria-label={t.socials}>{[['linkedin','LinkedIn'],['instagram','Instagram'],['cv',t.resume]].map(([key,label])=><a key={key} className="social-pill" href={profile[key]} target="_blank" rel="noreferrer"><Icon kind={key}/><span className="roll-label"><span>{label}</span><span aria-hidden="true">{label}</span></span></a>)}</div>}
function Nav({page,navigate,lang,setLang,t}){return <div className="topnav-wrap"><a className="topdock topdock--avatar rp-avatar" href="/" onClick={e=>navigate(e,'/')} aria-label={t.homeLabel}><img src="/assets/avatar-reference.jpeg" alt="Avatar ilustrado de Rafael Palmeira"/></a><nav className="topdock" aria-label={t.navigation}>{t.nav.map(([url,label])=><a key={url} href={url} onClick={e=>navigate(e,url)} className={'topdock__link '+(page===url?'is-active':'')} aria-current={page===url?'page':undefined}>{page===url&&<span className="topdock__pill"><span className="topdock__pill-fill"/></span>}<span className="topdock__label">{label}</span></a>)}</nav><div className="topdock language-switch" role="group" aria-label={t.language}>{['pt','en'].map(code=><button key={code} type="button" className={'language-switch__button '+(lang===code?'is-active':'')} aria-pressed={lang===code} onClick={()=>setLang(code)}>{code.toUpperCase()}</button>)}</div></div>}
function Greeting(){const words=['Olá','Hello','Hola','Bonjour'],[word,setWord]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const t=setInterval(()=>setWord(v=>(v+1)%4),5000);return()=>clearInterval(t)},[]);return <span className="home__hello-draw rp-hello" aria-hidden="true"><span key={word}>{Array.from(words[word]).map((letter,i)=><span key={i} style={{fontSize:`${.58+i*.125}em`,animationDelay:`${i*45}ms`}}>{letter}</span>)}</span></span>}
function Intro({t}){return <aside className="home__lead"><div className="home__lead-inner"><div className="home__identity"><Greeting/><div className="home__heading-row rp-identity"><img src="/assets/avatar-reference.jpeg" className="rp-mini-portrait" alt=""/><h1 className="home__hello"><span className="mobile-greeting">{t.mobileGreeting}</span>{t===ui.pt?'sou Rafael.':"I'm Rafael."}</h1></div></div><div className="home__intro"><div className="home__body">{t.intro.map((item,i)=><p key={item.title}><strong>{item.title}</strong> {item.before||item.text}{item.link&&<a href="/about/" className="home__link-pill" style={{'--brand':'#660099'}}>{item.link}</a>}{item.after}</p>)}</div><Socials t={t}/></div></div></aside>}
function Card({project,onOpen,t,active=true}){return <button className="rp-project" onClick={()=>onOpen(project)} aria-label={`${t.viewProject} ${project.title}`} tabIndex={active?0:-1}><img src={'/assets/'+project.image} alt={`${project.title}, ${project.discipline}`} loading={project.id==='bradesco'?'eager':'lazy'} decoding="async"/><span className="project-caption"><span className="project-arrow"><Icon/></span><span className="project-name">{project.title}</span></span></button>}
function Home({onOpen,projects,t}){
 const [current,setCurrent]=useState(0),[hasMoved,setHasMoved]=useState(false),lock=useRef(0),touch=useRef(null);
 const [deck,setDeck]=useState(()=>matchMedia('(min-width:761px) and (prefers-reduced-motion:no-preference)').matches);
 useEffect(()=>{const m=matchMedia('(min-width:761px) and (prefers-reduced-motion:no-preference)'),change=()=>setDeck(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);
 const step=useCallback(direction=>{if(Date.now()-lock.current<700)return;lock.current=Date.now();setHasMoved(true);setCurrent(v=>(v+direction+projects.length)%projects.length)},[]);
 useEffect(()=>{if(!deck)return;const wheel=e=>{if(document.querySelector('dialog[open]')||e.ctrlKey||Math.abs(e.deltaY)<10)return;e.preventDefault();step(e.deltaY>0?1:-1)},key=e=>{if(document.querySelector('dialog[open]')||e.target.closest('a,button'))return;if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();step(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)}};window.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',key);return()=>{window.removeEventListener('wheel',wheel);window.removeEventListener('keydown',key)}},[deck,step]);
 return <main id="main" className={'shell shell--home '+(deck?'rp-deck-page':'')}><div className="home"><Intro t={t}/><div className="home__stream">{deck?<div className="rp-deck" role="region" aria-label={t.carousel} onTouchStart={e=>touch.current=e.touches[0].clientY} onTouchEnd={e=>{const delta=touch.current-e.changedTouches[0].clientY;if(Math.abs(delta)>35)step(delta>0?1:-1)}}>{projects.map((p,i)=>{let offset=(i-current+projects.length)%projects.length;if(offset>projects.length/2)offset-=projects.length;return <div className={'rp-slide '+(offset===0?'is-front':'is-side')} key={p.id} aria-hidden={offset!==0} style={{'--step':offset,'--tilt':offset===0?'0deg':offset>0?'85deg':'-85deg',zIndex:10-Math.abs(offset),opacity:offset===0?1:Math.abs(offset)===1?.085:0,pointerEvents:offset===0?'auto':'none'}}><Card project={p} onOpen={onOpen} t={t} active={offset===0}/></div>})}</div>:<div className="rp-mobile-stream">{projects.map(p=><Card key={p.id} project={p} onOpen={onOpen} t={t}/>)}</div>}</div></div>{deck&&<><nav className="project-pagination" aria-label={t.selectProject}>{[-1,0,1].map(delta=>{const n=(current+delta+projects.length)%projects.length;return <button key={delta} aria-label={`${projects[n].title}, ${t.project} ${n+1} ${t.of} ${projects.length}`} aria-current={delta===0?'true':undefined} onClick={()=>{setCurrent(n);setHasMoved(true)}}><span/></button>})}</nav><div className={'carousel-hint '+(hasMoved?'carousel-hint--gone':'')}>{t.scroll} <Icon kind="down"/></div><p className="sr-only" aria-live="polite">{projects[current].title}, {current+1} {t.of} {projects.length}</p></>}</main>
}
function Work({onOpen,projects,filters,t}){const [filter,setFilter]=useState('todos'),shown=filter==='todos'?projects:projects.filter(p=>p.category===filter);return <main id="main" className="shell rp-work"><header className="work-intro"><p>{t.workKicker}</p><h1>{t.workTitle}</h1></header><div className="work-filters" role="group" aria-label={t.filter}>{filters.map((f,i)=><button className={'work-filter '+(filter===f.id?'is-selected':'')} key={f.id} aria-pressed={filter===f.id} aria-controls="work-results" onClick={()=>setFilter(f.id)}><span className="work-filter__art" aria-hidden="true" dangerouslySetInnerHTML={{__html:folders[i]}}/><span className="work-filter__caption">{f.label}</span></button>)}</div><p role="status" className="sr-only">{shown.length} {t.found}</p><div id="work-results" className="rp-work-grid" key={filter}>{shown.map(p=><Card key={p.id} project={p} onOpen={onOpen} t={t}/>)}</div></main>}
function About({experience,t,lang}){const spotifyAlbum='https://open.spotify.com/album/1a1d7otjF9oxSGHHlSGbmo?si=BLXttk7aR0CiV8AbqgyoGA&dl_branch=1&nd=1';return <main id="main" className="shell"><section className="about-page" aria-labelledby="about-title"><div className="about-layout"><article className="about-story-card"><h1 id="about-title">{t.about.title}</h1><hr className="about-story-card__divider"/><div className="about-story-card__prose">{t.about.blocks.map((block,i)=><p key={i}>{block.title&&<><strong>{block.title}</strong> </>}{block.text}</p>)}<p className="about-story-card__closer">{t.about.closer}<span>{t.about.closerAccent}</span></p></div><div className="about-sign"><img className="rp-signature" src="/assets/signature.png" alt="Rafael Palmeira"/></div></article><div className="about-cards"><div className="about-card about-card--photo rp-photo"><img src="/assets/portrait.png" alt={lang==='pt'?'Retrato de Rafael Palmeira com intervenções gráficas coloridas':'Portrait of Rafael Palmeira with colorful graphic elements'}/></div><section className="about-card rp-practice rp-listening" aria-labelledby="listening-title"><div className="practice-top"><div><h2 id="listening-title">{t.about.musicTitle}</h2><p>{t.about.musicText}</p></div><a href={spotifyAlbum} target="_blank" rel="noreferrer" className="spotify-link" aria-label={t.about.spotify}><span aria-hidden="true">●</span> Spotify</a></div><iframe className="spotify-player" title="Kaiser Chiefs on Spotify" src="https://open.spotify.com/embed/album/1a1d7otjF9oxSGHHlSGbmo?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allowFullScreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/><a className="rp-contact" href={profile.email}>{t.about.contact} <Icon/></a></section></div></div><section className="rp-experience" aria-labelledby="experience-title"><h2 id="experience-title">{t.about.experience}</h2><div>{experience.map(([company,period])=><div className="experience-row" key={company}><span>{company}</span><span>{period}</span></div>)}</div><Socials t={t}/></section></section></main>}
function ProjectDialog({project,onClose,t}){const ref=useRef(null);useEffect(()=>{const d=ref.current;if(project&&!d.open)d.showModal();if(!project&&d.open)d.close()},[project]);return <dialog ref={ref} className="rp-dialog" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} aria-labelledby="project-title"><button className="dialog-close" onClick={onClose} aria-label={t.close}><span aria-hidden="true">×</span></button>{project&&<div className="dialog-content"><img className="dialog-image" src={'/assets/'+project.image} alt={project.title}/><div className="dialog-copy"><span className="dialog-discipline">{project.discipline}</span><p className="dialog-project">{project.title}</p><h2 id="project-title">{project.headline}</h2><p>{project.description}</p><a href="https://www.rafapalmeira.work/" target="_blank" rel="noreferrer">{t.portfolio} <Icon/></a></div></div>}</dialog>}
export function App(){const normalize=p=>p==='/'?'/':p.replace(/\/$/,'')+'/';const [page,setPage]=useState(()=>normalize(location.pathname)),[project,setProject]=useState(null),[lang,setLang]=useState(getInitialLanguage);const t=ui[lang],projects=lang==='pt'?projectsPt:projectsEn,filters=lang==='pt'?filtersPt:filtersEn,experience=lang==='pt'?experiencePt:experienceEn;useEffect(()=>{const pop=()=>{setPage(normalize(location.pathname));setProject(null)};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);const navigate=(e,url)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();history.pushState({},'',url);setPage(url);setProject(null);window.scrollTo(0,0)};useEffect(()=>{document.documentElement.lang=lang;setProject(null);try{localStorage.setItem('rp-language',lang)}catch{}},[lang]);useEffect(()=>{document.title=page==='/about/'?t.titles.about:page==='/work/'?t.titles.work:t.titles.home;window.scrollTo(0,0)},[page,t]);return <><a className="skip-link" href="#main">{t.skip}</a><Nav page={page} navigate={navigate} lang={lang} setLang={setLang} t={t}/>{page==='/'?<Home onOpen={setProject} projects={projects} t={t}/>:page==='/work/'?<Work onOpen={setProject} projects={projects} filters={filters} t={t}/>:page==='/about/'?<About experience={experience} t={t} lang={lang}/>:<main className="shell rp-not-found"><h1>{t.notFound}</h1><a href="/" onClick={e=>navigate(e,'/')}>{t.back}</a></main>}<ProjectDialog project={project} onClose={()=>setProject(null)} t={t}/></>}
