export const profile={name:'Rafael Palmeira',role:'Product Design Lead · UX Strategy · IA e Produtos Digitais',location:'Campinas, SP',email:'mailto:dantaspalmeira@gmail.com',linkedin:'https://www.linkedin.com/in/dantaspalmeira/',instagram:'https://www.instagram.com/dantaspalmeira/',whatsapp:'https://api.whatsapp.com/send?phone=5511970941126',cv:'https://www.dropbox.com/scl/fi/nurca9ja6gcyxopcdexyn/Rafael_Palmeira_CV_EN.pdf?rlkey=6jf23kwnprngtmefy16142164&st=d6jevhzw&dl=0'};
// Only projects with complete, inspected images from Rafael's existing portfolio.
export const projectsPt=[
{id:'bradesco',title:'Bradesco',headline:'Escolher com clareza.',category:'produto',image:'bradesco.png',description:'Um portfólio amplo de cartões precisava ser mais simples de entender. A experiência organiza informação, comparação e descoberta para aproximar produto e decisão.',discipline:'Produto digital · Interface'},
{id:'adidas',title:'Adidas',headline:'Produto em movimento.',category:'visual',image:'adidas.jpg',description:'Uma linguagem visual que conecta produto, cultura urbana e composição gráfica. Cada elemento trabalha para construir energia, ritmo e reconhecimento.',discipline:'Design visual · Comunicação'},
{id:'nissan',title:'Nissan Sentra',headline:'Presença em cada detalhe.',category:'visual',image:'nissan.jpg',description:'Uma narrativa visual criada para apresentar o Nissan Sentra com precisão e personalidade. Imagem, tipografia e composição constroem uma experiência de marca coesa.',discipline:'Design visual · Comunicação'},
{id:'livro',title:'Histórias em páginas',headline:'Uma história que se percorre.',category:'editorial',image:'editorial-book.jpg',description:'Um projeto editorial sobre a trajetória de uma agência. Fotografia, ritmo e arquitetura da informação transformam memória em uma experiência de leitura.',discipline:'Design editorial · Publicação'},
{id:'tipografia-editorial',title:'Voz e tipografia',headline:'Tipografia que conduz.',category:'editorial',image:'editorial-type.jpg',description:'Escala, contraste e hierarquia dão voz ao conteúdo. O sistema tipográfico orienta a leitura e cria uma narrativa visual clara e expressiva.',discipline:'Design editorial · Tipografia'},
{id:'composicao',title:'Forma, letra e composição',headline:'Forma que vira sistema.',category:'editorial',image:'typography.jpg',description:'Estudos de forma, tipografia e estrutura que investigam como decisões visuais podem ganhar consistência sem perder personalidade.',discipline:'Design editorial · Composição'}
];
export const projectsEn=[
{id:'bradesco',title:'Bradesco',headline:'Choosing with clarity.',category:'produto',image:'bradesco.png',description:'A broad card portfolio needed to become easier to understand. The experience organizes information, comparison and discovery to bring products and decisions closer together.',discipline:'Digital product · Interface'},
{id:'adidas',title:'Adidas',headline:'Product in motion.',category:'visual',image:'adidas.jpg',description:'A visual language connecting product, urban culture and graphic composition. Every element works together to build energy, rhythm and recognition.',discipline:'Visual design · Communication'},
{id:'nissan',title:'Nissan Sentra',headline:'Presence in every detail.',category:'visual',image:'nissan.jpg',description:'A visual narrative created to present the Nissan Sentra with precision and personality. Imagery, typography and composition shape a cohesive brand experience.',discipline:'Visual design · Communication'},
{id:'livro',title:'Stories in pages',headline:'A story you move through.',category:'editorial',image:'editorial-book.jpg',description:'An editorial project about an agency’s journey. Photography, pacing and information architecture turn memory into a reading experience.',discipline:'Editorial design · Publication'},
{id:'tipografia-editorial',title:'Voice and typography',headline:'Typography that leads.',category:'editorial',image:'editorial-type.jpg',description:'Scale, contrast and hierarchy give the content a voice. The typographic system guides reading and creates a clear, expressive visual narrative.',discipline:'Editorial design · Typography'},
{id:'composicao',title:'Form, type and composition',headline:'Form becomes a system.',category:'editorial',image:'typography.jpg',description:'Studies in form, typography and structure exploring how visual decisions can gain consistency without losing personality.',discipline:'Editorial design · Composition'}
];
export const filtersPt=[{id:'todos',label:'Todos os trabalhos'},{id:'produto',label:'Product Design'},{id:'visual',label:'Design visual'},{id:'editorial',label:'Editorial'}];
export const filtersEn=[{id:'todos',label:'All work'},{id:'produto',label:'Product Design'},{id:'visual',label:'Visual design'},{id:'editorial',label:'Editorial'}];
export const experiencePt=[['Vivo · Telefônica Brasil','2023 até hoje'],['Nestlé','2021 a 2023'],['Ernst & Young','2020 a 2021'],['Publicis Groupe · Sapient AG2','2019 a 2020'],['TeamWorker','2018 a 2019']];
export const experienceEn=[['Vivo · Telefônica Brasil','2023 to present'],['Nestlé','2021 to 2023'],['Ernst & Young','2020 to 2021'],['Publicis Groupe · Sapient AG2','2019 to 2020'],['TeamWorker','2018 to 2019']];
